### ISSUE TITLE
The demo for example (/examples/resources/) is not valid. After the maven package is packaged, the package structure and resource contents of the jar file are not changed.

### ISSUE THREAD

**Issue by xhc-code** [yWorks/yGuard#133]
The demo for example (/examples/resources/) is not valid. After the maven package is packaged, the package structure and resource contents of the jar file are not changed.

**Comment by thomasbehr** [comment]
You are right, that demo does not work as intended. We will try to improve the demo for a future version of yGuard.

If you need to adjust resource file names and resource file contents, use a single `adjust` element instead of three:
```
<adjust replaceContent="true" replaceContentSeparator="." replaceName="true">
  <include name="**/*.properties"/>
</adjust>
```
Please see the [adjust element documentation](https://yworks.github.io/yGuard/task_documentation.html#the-adjust-element) for further configuration options and examples.
