### ISSUE TITLE
yguard

### ISSUE THREAD

**Issue by ThanhDat2804** [yWorks/yGuard#163]
when i build obfuscate with yguard but it show error 
Error: Main method not found in class B.A.A.A.G.I, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

**Comment by thomasbehr** [comment]
Well, you probably need to adjust your yGuard configuration. Take a look at the [rename element documentation](https://yworks.github.io/yGuard/task_documentation.html#the-rename-element) (especially the `mainClass` attribute) and the [application example](https://github.com/yWorks/yGuard/tree/master/examples/application) that comes with yGuard.

If the above does not help, please post your yGuard configuration and provide information about your application (main class, how you run the application, etc.).

**Comment by thomasbehr** [comment]
> u teamview or something

No, for multiple reasons. ;-)

Spring and Spring Boot heavily rely on a technique called "reflection". Obfuscation does not work together with reflection. For this reason I strongly recommend not obfuscating your Spring Boot project at all.

If you need to use obfuscation because of legal requirement, postpone obfuscation until you have at least journeyman-level understanding of Spring Boot. Once you reached that point, please see the [processing example](https://github.com/yWorks/yGuard/tree/master/examples/processing) and the [Yguard Obfuscation in a Spring Boot Project](https://github.com/yWorks/yGuard/issues/43) topic for further information on obfuscation Spring Boot applications.
