### ISSUE TITLE
improve documentation on <attribute>

### ISSUE THREAD

**Issue by Fohlen** [yWorks/yGuard#20]
where should it be placed?
works both as a child of `<yguard>` and of `<keep>`, but doesn't work as a child of `<rename>`.

@micschro suggested:
placing it as a child of `<rename>` should yield an error message?

**Comment by Fohlen** [comment]
Placing it as a child of `yguard` makes no sense. It currently can be placed anywhere. However so, it should only be a child of the `shrink` task. Fix this.

**Comment by thomasbehr** [comment]
Wait a second, the <attribute> element does affect renaming as well as shrinking. Even if renaming but not shrinking, yGuard is able (or rather will) remove (optional) attributes from class files. While it may seem counter-intuitive to remove attributes when renaming but not shrinking, this actually make sense because removing attributes like SourceFile, LineNumberTable, LocalVariableTable actually serves the purpose of increasing the difficulty for reverse engineering which is the whole point of obfuscation.

Moreover, if <attribute> was only allowed for shrinking, we would need a "remove only attributes but no classes/members" mode for shrinking. Which in turn would require additional configuration for "obfuscation only" use cases.

I vote to keep <attribute> as is.

**Comment by Fohlen** [comment]
Judging from the source code, the `attributesSections` variable is currently (even before this PR) respected ONLY in the shrinker. I think we are talking about the `attribute` child element for the rename task then? Why are they named the same (confusing)?

**Comment by Fohlen** [comment]
The `attribute` section described is actually correct behavior as pointed out by @thomasbehr
Closing.
